import { Poppins } from "next/font/google";
import "./globals.css";
import Sidebar, { Menu } from "./_sidebar";
import clsx from "clsx";

const poppins = Poppins({
  weight: ["100", "200", "300", "400", "500", "600", "700", "800", "900"],
  subsets: ["latin"],
  variable: "--font-poppins",
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={clsx("flex font-poppins font-medium", poppins.variable)}>
        <Sidebar />
        <div className="flex-grow">{children}</div>
      </body>
    </html>
  );
}
